FROM mattiasegly/base-image:amd64

ENV NODE_ENV="production"

ARG SOURCE=https://nodejs.org/download/release
ARG RELEASE=15.2.1
ARG ARCH=x64

RUN curl -L $SOURCE/v$RELEASE/node-v$RELEASE-linux-$ARCH.tar.gz -o node.tar.gz && \
	tar -xzf node.tar.gz -C /usr/local --strip-components=1 && \
	rm node.tar.gz && \
	npm config set unsafe-perm true && \
	npm config set user root && \
	node --version